# Header
menu:
  Home: /
  Tags: /tags
  Archives: /archives
  Talks: /talks
  About Me: /about
  CV: https://estebantorr.es/cv
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-47828981-1
favicon: /favicon.png
