# Header
menu:
  Home: /
  About Me: /about
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-47828981-1
favicon: /favicon.png
